# Generated by Django 3.0.5 on 2020-05-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registr', '0002_user_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
