# Generated by Django 3.0.5 on 2020-05-06 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registr', '0004_state_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='reg_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
