# Generated by Django 3.0.5 on 2020-05-10 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registr', '0005_state_reg_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_event', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('time', models.DateTimeField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='event',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='registr.Event'),
            preserve_default=False,
        ),
    ]
