# Generated by Django 3.0.5 on 2020-05-10 13:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registr', '0006_auto_20200510_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 13, 19, 0, 536704, tzinfo=utc)),
        ),
    ]
