# Generated by Django 3.0.5 on 2020-05-10 14:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registr', '0007_auto_20200510_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name_event',
            new_name='event_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 14, 42, 36, 25419, tzinfo=utc)),
        ),
    ]
